import requests

# Replace this with your actual Bearer Token
bearer_token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Ii1samxJbGlVMlZvZVZwVlRHY00zWXRiZVdxbjBSVERBVTg3X2FmSlNLem8iLCJhbGciOiJSUzI1NiIsIng1dCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCIsImtpZCI6IjNQYUs0RWZ5Qk5RdTNDdGpZc2EzWW1oUTVFMCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84MmE4NDVjZS0wMDQyLTRhMDgtYTJmMS03MzRmYmRjMzQ4MDYvIiwiaWF0IjoxNzMxNjA1MzYxLCJuYmYiOjE3MzE2MDUzNjEsImV4cCI6MTczMTYxMDcyOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhZQUFBQVZMQUZ6Mi9ybW1pekhNTG41RUxjTWNUbEJoeUlycDY1bEdhRVpvL3dKbkhKbUFEWEh3Z0JSQllBbFhnN1NIYUkiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik15IFByb2ZpbGUiLCJhcHBpZCI6IjhjNTllYWQ3LWQ3MDMtNGEyNy05ZTU1LWM5NmEwMDU0YzhkMiIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiZDNiNTI2N2MtY2IyNC00NjIyLWEzODItYTYwZDkxMDU4NjA4IiwiZmFtaWx5X25hbWUiOiJHYWxicmVhdGgiLCJnaXZlbl9uYW1lIjoiSmFrZSIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjE4NS4xOTMuMTU3LjQyIiwibmFtZSI6IkdhbGJyZWF0aCwgSmFrZSIsIm9pZCI6IjA0NzEyOTQxLTdkN2QtNDEzMy05MjYxLTA4OTkwMDBmZjA5MCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xMDE5Njk1MTczLTE3ODU0NzM1MjEtMTg0NzkyODA3NC0yMjAzOTEiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDAzRUUyMDU5MyIsInJoIjoiMS5BUVFBemtXb2drSUFDRXFpOFhOUHZjTklCZ01BQUFBQUFBQUF3QUFBQUFBQUFBQUVBYzhFQUEuIiwic2NwIjoiQXVkaXRMb2cuUmVhZC5BbGwgQml0bG9ja2VyS2V5LlJlYWQuQWxsIENyb3NzVGVuYW50SW5mb3JtYXRpb24uUmVhZEJhc2ljLkFsbCBDcm9zc1RlbmFudFVzZXJQcm9maWxlU2hhcmluZy5SZWFkV3JpdGUuQWxsIERldmljZS5FbmFibGVEaXNhYmxlQWNjb3VudC5BbGwgRGV2aWNlLlJlYWQuQWxsIGVtYWlsIEdyb3VwLlJlYWQuQWxsIEdyb3VwLlJlYWRXcml0ZS5BbGwgR3JvdXBNZW1iZXIuUmVhZC5BbGwgTWFpbGJveFNldHRpbmdzLlJlYWRXcml0ZSBvcGVuaWQgT3JnYW5pemF0aW9uLlJlYWQuQWxsIFBvbGljeS5SZWFkLkFsbCBwcm9maWxlIFJvbGVNYW5hZ2VtZW50LlJlYWRXcml0ZS5EaXJlY3RvcnkgVXNlci5JbnZpdGUuQWxsIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIiwic2lnbmluX3N0YXRlIjpbImR2Y19tbmdkIiwiZHZjX2NtcCJdLCJzdWIiOiJWc29BdWZ1c3AxcHo0QUNPTlhybWd5NmtVWWF5alFjeVFsNFNhdjgwWk5JIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6Ik5BIiwidGlkIjoiODJhODQ1Y2UtMDA0Mi00YTA4LWEyZjEtNzM0ZmJkYzM0ODA2IiwidW5pcXVlX25hbWUiOiJqYWtlZzM3NjNAdHVzdGluLmsxMi5jYS51cyIsInVwbiI6Impha2VnMzc2M0B0dXN0aW4uazEyLmNhLnVzIiwidXRpIjoiT3JMTGt5Mlg5a2VBcHhaSGNXcHdBUSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgMjQiLCJ4bXNfc3QiOnsic3ViIjoiakN4UnhFZFpQWDhiN2VSTXZocDJlZWRZNVE1d1dDbVpDR0ZMSlJVUjVTZyJ9LCJ4bXNfdGNkdCI6MTM2MTM3ODAyN30.ftRSZRO_Qk5g7k0clq4bztUOvSDMCFk-6W8YmPFr4fLYwZdH2C0MSN7QL1mw0yhmSWU8IR3b_x3hSUA6csrNFodK0itMeAELbKfoH69xQ6HhcvhJGUyVc07JYAKuQ4H1gRs5o8Yj7e1BBb8LR_P4_FyBvjGFSX7kCcwJ7U3TRUbSDqIXdhuVtNDaJPr9WbWCWYZtSmLnVX1yY-rrBDyfoKU5oXbsJVHOHX314Z2hBifEVQCWRDAeir-k_8N1DddrHZyg1PyIhKCfU8cNiJHcs6xFsMnDxvMhaaOzb5ofLbIytbjf1fpt0aPV2FQMIv1ZT1FvI6Mn5ZuoY6j08MVSMw"

# URL of the API endpoint you're trying to access
url = "https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys/340cbdc9-a87c-4c06-93c7-7cb4e6d87443?$select=key"

# Set up the headers to include the bearer token
headers = {
    "Authorization": f"Bearer {bearer_token}",
    "Content-Type": "application/json"  # Optional, if the server expects JSON data
}

# Example GET request using the bearer token
response = requests.get(url, headers=headers)

# Check if the request was successful (HTTP status 200)
if response.status_code == 200:
    print("Request successful!")
    print(response.json())  # Assuming the response is JSON
else:
    print(f"Request failed with status code {response.status_code}")
    print(response.text)
